import os
from dotenv import load_dotenv
import warnings
warnings.filterwarnings("ignore", category=UserWarning, module="wikipedia")

load_dotenv()

print("1. [app.py] Environment variables loaded successfully.")

try:
    from graph.workflow import travel_assistant_graph

    print("2. [app.py] Workflow graph successfully compiled and imported.")
except Exception as e:
    print(f" CRITICAL IMPORT ERROR inside graph setup: {e}")
    import traceback

    traceback.print_exc()


def run_travel_assistant():
    print(" Starting AI Travel Orchestrator MVP...")

    config = {"configurable": {"thread_id": "mvp_test_trip_2026"}}
    initial_state = {
        "current_task_from_human": "Flight from Paris to Rome, 5 days, start from June 5, 2026, 1000$ budget",
        "messages": []
    }

    final_state = None

    try:
        for event in travel_assistant_graph.stream(initial_state, config):
            final_state = event
            for node_name, output in event.items():
                print(f"\n [NODE] '{node_name}' finished execution.")

                if "messages" in output and output["messages"]:
                    last_msg = output["messages"][-1]
                    if last_msg.content:
                        print(f" Message: {last_msg.content}")

                if "next_agent" in output:
                    print(f" Target next agent: '{output['next_agent']}'")

                if node_name == "planner":
                    print(
                        f" State Updated -> Flights counter: {len(output.get('flight_options', []))}, Hotels counter: {len(output.get('hotel_options', []))}")
                elif node_name == "guide":
                    print(f" State Updated -> Route days: {list(output.get('route_by_day', {}).keys())}")
                elif node_name == "budget":
                    print(f" State Updated -> Financial Verdict: {output.get('budget_status', '')}")

        # =====================================================================
        # Final block
        # =====================================================================
        print("\n Orchestrator compiling the final document on disk...")

        # get actual state from snapshot
        state_snapshot = travel_assistant_graph.get_state(config)
        data = state_snapshot.values

        flights = data.get("flight_options", [])
        hotels = data.get("hotel_options", [])
        route = data.get("route_by_day", {})
        facts = data.get("interesting_facts", "")
        budget = data.get("budget_status", "")
        total = data.get("total_cost", 0.0)

        md_content = f"""# YOUR PERSONAL TRAVEL ITINERARY REPORT
    Generated by AI Multi-Agent System via LangGraph

    ## Trip Overview
    * **Destination:** Rome, Italy
    * **Duration:** 5 Days (Start: June 5, 2026)
    * **Financial Status:** {budget}

    ---

    ## Logistics: Flights Found

    | Airline | Flight Number | Price | Duration |
    |---------|---------------|-------|----------|
    """
        for f in flights:
            md_content += f"| {f.get('airline')} | {f.get('flight_number')} | ${f.get('price')} | {f.get('duration')} mins |\n"

        md_content += f"""
    ## Logistics: Accommodations

    | Hotel Name | Price per Night | Rating | Reviews |
    |------------|-----------------|--------|---------|
    """
        for h in hotels:
            md_content += f"| {h.get('name')} | ${h.get('price')} | {h.get('rating')} | {h.get('reviews')} |\n"

        md_content += f"""
    ---

    ## Cultural Day-by-Day Itinerary
    """
        for day, schedule in route.items():
            md_content += f"### {day}\n{schedule}\n\n"

        md_content += f"""
    ---

    ## Local Insights & Interesting Facts
    {facts}

    ---
    *Report successfully compiled by AI Travel Orchestrator System. Enjoy your trip!*
    """
        # write to file
        file_path = "final_travel_plan.md"
        with open(file_path, "w", encoding="utf-8") as f_out:
            f_out.write(md_content)

        print(f"SUCCESS! Beautiful report saved to file: '{os.path.abspath(file_path)}'")

    except Exception as e:
        print(f"\n An error occurred during graph execution: {e}")


if __name__ == "__main__":
    if not os.getenv("GROQ_API_KEY"):
        print("Error: GROQ_API_KEY is missing in your .env file!")
    else:
        run_travel_assistant()
